"""add display_name to trip_members for shadow member support

Revision ID: 2f3658f35179
Revises: 0be639069751
Create Date: 2026-08-14 14:49:08.348219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3658f35179'
down_revision: Union[str, None] = '0be639069751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_members', sa.Column('display_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_members', 'display_name')
    # ### end Alembic commands ###
